name: Check Version Number

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 2 # We need to fetch at least two commits for comparison

      - name: Get version from main
        id: get_main_version
        run: |
          VERSION_MAIN=$(cat pyproject.toml | grep '^version =' | awk -F'"' '{print $2}')
          echo "VERSION_MAIN=$VERSION_MAIN" >> $GITHUB_ENV

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Get version from PR
        id: get_pr_version
        run: |
          VERSION_PR=$(cat pyproject.toml | grep '^version =' | awk -F'"' '{print $2}')
          echo "VERSION_PR=$VERSION_PR" >> $GITHUB_ENV

      - name: Compare versions
        run: |
          if [ "$VERSION_MAIN" = "$VERSION_PR" ]; then
            echo "Version in pyproject.toml not updated. Please update."
          echo "Version on main: $VERSION_MAIN"
          echo "Version on PR: $VERSION_PR"
            exit 1
          fi
          if [ "$(printf '%s\n' "$VERSION_MAIN" "$VERSION_PR" | sort -V | head -n1)" = "$VERSION_PR" ]; then
            echo "Version in PR is older than version in main. Failing the check."
            echo "Version on main: $VERSION_MAIN"
            echo "Version on PR: $VERSION_PR"
            exit 1
          fi
          echo "Version numbers are different and PR version is not older. Check passed."
          echo "Version on main: $VERSION_MAIN"
          echo "Version on PR: $VERSION_PR"
          
